artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/415011694305976472/a9046bb741b84b30bfa8b31b12bbe60e/artifacts
end_time: 1769783372900
entry_point_name: ''
experiment_id: '415011694305976472'
lifecycle_stage: active
run_id: a9046bb741b84b30bfa8b31b12bbe60e
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783372804
status: 3
tags: []
user_id: agiannoul
