artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/997267698133755630
creation_time: 1769783347906
experiment_id: '997267698133755630'
last_update_time: 1769783347906
lifecycle_stage: active
name: RUL HNEI sktimeFCN
