artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/968336206638657292
creation_time: 1769783366548
experiment_id: '968336206638657292'
last_update_time: 1769783366548
lifecycle_stage: active
name: RUL Azure sktimeInceptionTime
