artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/287430205073373616/8c67ce39b3de4cd4b9c6ad87c3ddf266/artifacts
end_time: 1769783346440
entry_point_name: ''
experiment_id: '287430205073373616'
lifecycle_stage: active
run_id: 8c67ce39b3de4cd4b9c6ad87c3ddf266
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783346359
status: 3
tags: []
user_id: agiannoul
