artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/796868646699627453
creation_time: 1769783408028
experiment_id: '796868646699627453'
last_update_time: 1769783408028
lifecycle_stage: active
name: SA Azure GradientBoosting
