artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/287430205073373616
creation_time: 1769783346356
experiment_id: '287430205073373616'
last_update_time: 1769783346356
lifecycle_stage: active
name: RUL HNEI sktimeResNet
