artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/449289639420282660
creation_time: 1769783374340
experiment_id: '449289639420282660'
last_update_time: 1769783374340
lifecycle_stage: active
name: RUL Azure RandomForestRUL
