artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/462541716078504904
creation_time: 1769783406463
experiment_id: '462541716078504904'
last_update_time: 1769783406463
lifecycle_stage: active
name: SA SCANIA DeepHit
