artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/991036365521509833
creation_time: 1769783383539
experiment_id: '991036365521509833'
last_update_time: 1769783383539
lifecycle_stage: active
name: RUL SCANIA sktimeLSTMFCN
