artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/131744143843142444
creation_time: 1769783381990
experiment_id: '131744143843142444'
last_update_time: 1769783381990
lifecycle_stage: active
name: RUL SCANIA sktimeInceptionTime
