artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/914347447874829874
creation_time: 1769783391318
experiment_id: '914347447874829874'
last_update_time: 1769783391318
lifecycle_stage: active
name: RUL SCANIA ElasticNetRUL
