artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/321954609076374479
creation_time: 1769783377436
experiment_id: '321954609076374479'
last_update_time: 1769783377436
lifecycle_stage: active
name: RUL SCANIA sktimeResNet
