artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/520970161195839227
creation_time: 1769783352666
experiment_id: '520970161195839227'
last_update_time: 1769783352666
lifecycle_stage: active
name: RUL HNEI sktimeLSTMFCN
