artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/914142841970064316/5dc285841fcc4c4baecbda49eaeaa7f0/artifacts
end_time: 1769783388388
entry_point_name: ''
experiment_id: '914142841970064316'
lifecycle_stage: active
run_id: 5dc285841fcc4c4baecbda49eaeaa7f0
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783388259
status: 3
tags: []
user_id: agiannoul
