artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/649274258202726997
creation_time: 1769783361911
experiment_id: '649274258202726997'
last_update_time: 1769783361911
lifecycle_stage: active
name: RUL Azure sktimeResNet
