artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/316658363187881927
creation_time: 1769783378957
experiment_id: '316658363187881927'
last_update_time: 1769783378957
lifecycle_stage: active
name: RUL SCANIA sktimeFCN
