artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/886379705803063648/b9dbc5a75b5644578a0edd862796e9cf/artifacts
end_time: 1769783326635
entry_point_name: ''
experiment_id: '886379705803063648'
lifecycle_stage: active
run_id: b9dbc5a75b5644578a0edd862796e9cf
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783326557
status: 3
tags: []
user_id: agiannoul
