artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/129689657251104159
creation_time: 1769783351049
experiment_id: '129689657251104159'
last_update_time: 1769783351049
lifecycle_stage: active
name: RUL HNEI sktimeInceptionTime
