artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/385598191446132569/8c4c2289ff6143b28a3ccdd05eff5eae/artifacts
end_time: 1769783403585
entry_point_name: ''
experiment_id: '385598191446132569'
lifecycle_stage: active
run_id: 8c4c2289ff6143b28a3ccdd05eff5eae
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783403492
status: 3
tags: []
user_id: agiannoul
