artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/312635779307514396/9e7db0e77af94af5a2b6068dd9d9a48b/artifacts
end_time: 1769783368204
entry_point_name: ''
experiment_id: '312635779307514396'
lifecycle_stage: active
run_id: 9e7db0e77af94af5a2b6068dd9d9a48b
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783368097
status: 3
tags: []
user_id: agiannoul
