artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/110380723973207061
creation_time: 1769783363458
experiment_id: '110380723973207061'
last_update_time: 1769783363458
lifecycle_stage: active
name: RUL Azure sktimeFCN
