artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/525914710329600729
creation_time: 1769783360385
experiment_id: '525914710329600729'
last_update_time: 1769783360385
lifecycle_stage: active
name: RUL HNEI ElasticNetRUL
