artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/886393145330263787
creation_time: 1769783385153
experiment_id: '886393145330263787'
last_update_time: 1769783385153
lifecycle_stage: active
name: RUL SCANIA XGBoost
