artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/928602906949605801
creation_time: 1769783371210
experiment_id: '928602906949605801'
last_update_time: 1769783371210
lifecycle_stage: active
name: RUL Azure CatBoost_W_RUL
