artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/541823294636874861
creation_time: 1769783335636
experiment_id: '541823294636874861'
last_update_time: 1769783335636
lifecycle_stage: active
name: SA SCANIA05 GradientBoosting
