artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/165203065472714718/bc3406ec231548aaab5e012a1feafccc/artifacts
end_time: 1769783365091
entry_point_name: ''
experiment_id: '165203065472714718'
lifecycle_stage: active
run_id: bc3406ec231548aaab5e012a1feafccc
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783364990
status: 3
tags: []
user_id: agiannoul
