artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/991036365521509833/d7ef523e612140da9ba7c78e70e718aa/artifacts
end_time: 1769783383670
entry_point_name: ''
experiment_id: '991036365521509833'
lifecycle_stage: active
run_id: d7ef523e612140da9ba7c78e70e718aa
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783383541
status: 3
tags: []
user_id: agiannoul
