artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/317439763135420225/9b9ec1be0c0b4e56ba1352d5a122a664/artifacts
end_time: 1769783354342
entry_point_name: ''
experiment_id: '317439763135420225'
lifecycle_stage: active
run_id: 9b9ec1be0c0b4e56ba1352d5a122a664
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783354224
status: 3
tags: []
user_id: agiannoul
