artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/914347447874829874/7c76e94dd94d45fd8ca47efa9f3e7100/artifacts
end_time: 1769783391432
entry_point_name: ''
experiment_id: '914347447874829874'
lifecycle_stage: active
run_id: 7c76e94dd94d45fd8ca47efa9f3e7100
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783391320
status: 3
tags: []
user_id: agiannoul
