artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/516569560298941343/d47f9cc2de214f9a875fe6ad8558b5e6/artifacts
end_time: 1769783323619
entry_point_name: ''
experiment_id: '516569560298941343'
lifecycle_stage: active
run_id: d47f9cc2de214f9a875fe6ad8558b5e6
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783323534
status: 3
tags: []
user_id: agiannoul
