artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/655633572101608007
creation_time: 1769783320504
experiment_id: '655633572101608007'
last_update_time: 1769783320504
lifecycle_stage: active
name: SA HNEI05 GradientBoosting
