artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/191826978080063556
creation_time: 1769783369643
experiment_id: '191826978080063556'
last_update_time: 1769783369643
lifecycle_stage: active
name: RUL Azure XGBoost
