artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/238589241255591117
creation_time: 1769783343274
experiment_id: '238589241255591117'
last_update_time: 1769783343274
lifecycle_stage: active
name: SA HNEI GradientBoosting
