artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/899297465089676786/f4002afd7d574588b0d60aa1de36ccd9/artifacts
end_time: 1769783331185
entry_point_name: ''
experiment_id: '899297465089676786'
lifecycle_stage: active
run_id: f4002afd7d574588b0d60aa1de36ccd9
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783331090
status: 3
tags: []
user_id: agiannoul
