artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/558161803395491040
creation_time: 1769783409591
experiment_id: '558161803395491040'
last_update_time: 1769783409591
lifecycle_stage: active
name: SA SCANIA GradientBoosting
