artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/470121161973084345/3fbca99eeaf746be878270dea103b8d3/artifacts
end_time: 1769783389927
entry_point_name: ''
experiment_id: '470121161973084345'
lifecycle_stage: active
run_id: 3fbca99eeaf746be878270dea103b8d3
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783389801
status: 3
tags: []
user_id: agiannoul
