artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/449289639420282660/c730af2736e8471ebaad34b9cd27ddf4/artifacts
end_time: 1769783374444
entry_point_name: ''
experiment_id: '449289639420282660'
lifecycle_stage: active
run_id: c730af2736e8471ebaad34b9cd27ddf4
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783374343
status: 3
tags: []
user_id: agiannoul
