artifact_uri: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/851091676189476671/cc9fe23787cc4553b5ab1c0ce7894d65/artifacts
end_time: 1769783316047
entry_point_name: ''
experiment_id: '851091676189476671'
lifecycle_stage: active
run_id: cc9fe23787cc4553b5ab1c0ce7894d65
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1769783315993
status: 3
tags: []
user_id: agiannoul
