artifact_location: /home/agiannoul/Desktop/gitProjects/mypandora/piblicMlflow/mlruns/136605254467584705
creation_time: 1769783380470
experiment_id: '136605254467584705'
last_update_time: 1769783380470
lifecycle_stage: active
name: RUL SCANIA sktimeCNN
